version: '3'
services:
  db:
    image: world-db:1
    expose:
      - "9090"
    ports:
      - "9090:5432"
    restart: unless-stopped
    network_mode: bridge
    container_name: db

  #API**************************************
  api:
    image: world-api:1
    network_mode: bridge
    container_name: api
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db